init
bigronimax/T_Project pull request #1
Opened 2024-10-15 21:07 UTC by bigronimax

2024-10-16 07:32 UTC, mkRustam commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
А у тебя для этого проекта .gitignore не создался?

Если что вот сам файл
https://github.com/github/gitignore/blob/main/Android.gitignore
Заодно посмотри как правильно добавлять gitignore в проект и для чего он нужен

2024-10-16 07:33 UTC, mkRustam approved these changes

2024-10-21 07:36 UTC, mkRustam requested changes

2024-10-21 07:36 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Animal.kt
> +abstract class Animal {
А почему не интерфейс?

2024-10-21 09:07 UTC, mkRustam requested changes

2024-10-21 09:07 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Dog.kt
> +    val bite: BiteType
Иногда лучше полностью расписывать название переменной на основе ее типа, то есть `bite: BiteType` -> `biteType: BiteType`, в случае с behavior то же самое

2024-10-21 09:07 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/ZooMarket.kt
> +    fun catOrDog(animal: Animal): String {
Если в проекте добавится еще один тип животного, то придется переименовывать метод. Нужно какое-то абстрактное название для таких случаев

2024-10-21 09:07 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Husky.kt
> +class Husky(override var age: Int, override var weight: Float) : Animal(), Dog {
` : Animal(), Dog` - выглядит что нарушается иерархия. По сути каждая собака - это же животное, поэтому тут стоит немного иначе сделать

2024-10-21 09:07 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/ScottishCat.kt
> +class ScottishCat(override var age: Int, override var weight: Float) : Animal(), Cat {
`: Animal(), Cat` - здесь то же самое, каждый кот - это животное, поэтому стоит подумать над иерархией

2024-10-21 15:16 UTC, bigronimax commented on app/src/main/java/com/example/t_project/ZooMarket/Animal.kt
> +abstract class Animal {
Структурно хотелось выделить абстрактный класс для тех полей, методов, которые точно будут у каждого животного. Интерфейсы же являются модификациями (bite, behavior) с полями, которые соответствуют конкретному виду (собака, кошка). То есть абстрактный класс обобщенный, а интерфейсы для конкретных видов.

2024-10-21 15:16 UTC, bigronimax commented on app/src/main/java/com/example/t_project/ZooMarket/Dog.kt
> +    val bite: BiteType
Угу, понял

2024-10-21 15:21 UTC, bigronimax commented on app/src/main/java/com/example/t_project/ZooMarket/Husky.kt
> +class Husky(override var age: Int, override var weight: Float) : Animal(), Dog {
Не очень понял.. Хаски является животным и наследует все методы и поля, которые соответствуют всем животным. В то же время Хаски является собакой, поэтому наследуется от соответствующего интерфейса с полями и методами, которые подходят собакам.

2024-10-21 18:36 UTC, mkRustam requested changes

2024-10-21 18:36 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Animal.kt
> +abstract class Animal {
Понял твою мысль.

**Насчет абстрактного класса**
Если абстрактный класс не содержит никакой логики (нет реализации методов/полей/...), и в нем только объявление полей/методов, то лучше использовать интерфейс.

**Насчет модификаций**
Если я правильно понял что ты подразумеваешь под модификацией, то интерфейсы были бы модификациями если бы они выглядели так:

DogWithStraightBite
\+ fun eatWithProblems()

CatWithActiveBehavior
\+ fun runAndJump()

Но в данной задаче интерфейсы Cat и Dog являются частью иерархии, то есть должно выглядеть так
![image](https://github.com/user-attachments/assets/009599bb-0515-4b8a-ab6e-a6db0c2efacb)

А текущая архитектура выглядит так
![image](https://github.com/user-attachments/assets/286bc81d-dc01-42e3-8467-14b97883c356)
То есть складывается впечатление, что Собака и Кот не являются частью Животного мира

2024-10-21 18:36 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Husky.kt
> +class Husky(override var age: Int, override var weight: Float) : Animal(), Dog {
Ответил в комментарии к Animal

2024-10-21 19:00 UTC, bigronimax commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Добавил

2024-10-21 19:03 UTC, bigronimax commented on app/src/main/java/com/example/t_project/ZooMarket/Animal.kt
> +abstract class Animal {
Поменял структуру и убрал абстрактный класс. В таком случае наследование от абстрактных классов не сильно полезно использовать, если еще учесть, что интерфейсы позволяют реализовывать множественное наследование? Создавать отдельные классы для кота, собаки и т.д. звучит сильно громоздко в отличие от интерфейсов

2024-10-21 19:03 UTC, bigronimax commented on app/src/main/java/com/example/t_project/ZooMarket/ZooMarket.kt
> +    fun catOrDog(animal: Animal): String {
Поменял

2024-10-25 09:25 UTC, mkRustam commented on app/src/main/java/com/example/t_project/ZooMarket/Animal.kt
> +abstract class Animal {
Абстрактные классы уместно использовать когда есть базовая логика, которую требуется частично изменить в ее наследниках

2024-10-25 09:27 UTC, mkRustam approved these changes

2024-11-10 17:57 UTC, closed without merging